In [1]:
import os
import urllib.request

if not os.path.exists("the-verdict.txt"):
    url = "https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/refs/heads/main/ch02/01_main-chapter-code/the-verdict.txt"
    file_path = "the-verdict.txt"
    urllib.request.urlretrieve(url, file_path)

In [2]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [3]:
len(raw_text)

20484

In [4]:
import re

text = "Hello, world. This, is a test."
result = re.split(r'(\s)', text)

print(result)

['Hello,', ' ', 'world.', ' ', 'This,', ' ', 'is', ' ', 'a', ' ', 'test.']


In [5]:
result = re.split(r'([,.]|\s)', raw_text)
print(result)

['I', ' ', 'HAD', ' ', 'always', ' ', 'thought', ' ', 'Jack', ' ', 'Gisburn', ' ', 'rather', ' ', 'a', ' ', 'cheap', ' ', 'genius--though', ' ', 'a', ' ', 'good', ' ', 'fellow', ' ', 'enough--so', ' ', 'it', ' ', 'was', ' ', 'no', ' ', 'great', ' ', 'surprise', ' ', 'to', ' ', 'me', ' ', 'to', ' ', 'hear', ' ', 'that', ',', '', ' ', 'in', ' ', 'the', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory', ',', '', ' ', 'he', ' ', 'had', ' ', 'dropped', ' ', 'his', ' ', 'painting', ',', '', ' ', 'married', ' ', 'a', ' ', 'rich', ' ', 'widow', ',', '', ' ', 'and', ' ', 'established', ' ', 'himself', ' ', 'in', ' ', 'a', ' ', 'villa', ' ', 'on', ' ', 'the', ' ', 'Riviera', '.', '', ' ', '(Though', ' ', 'I', ' ', 'rather', ' ', 'thought', ' ', 'it', ' ', 'would', ' ', 'have', ' ', 'been', ' ', 'Rome', ' ', 'or', ' ', 'Florence', '.', ')', '\n', '', '\n', '"The', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory"--that', ' ', 'was', ' ', 'what', ' ', 'the', ' ', 'women', ' ', 'called', ' ', 'it

In [6]:
result = [item for item in result if item.strip()]
preprocessed = result
print(preprocessed)

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius--though', 'a', 'good', 'fellow', 'enough--so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"The', 'height', 'of', 'his', 'glory"--that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing--his', 'last', 'Chicago', 'sitter--deploring', 'his', 'unaccountable', 'abdication', '.', '"Of', 'course', "it's", 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'way", 'up;', 'but', 'I', "don't", 'think', 'of', 'that', ',', 'Mr', '.', 'Rickham--the', 'loss', 'to', 'Arrt', 'is', 'all', 'I', 'think', '

In [7]:
print(len(preprocessed))

4093


In [8]:
all_words = sorted(set(preprocessed))
print(all_words)

['"', '"Ah', '"Ah--I', '"Be', '"By', '"Come', '"Destroyed', '"Don\'t', '"Gisburns"', '"Grindles', '"Hang', '"Has', '"How', '"I', '"I\'d', '"If', '"It', '"It\'s', '"Jack', '"Money\'s', '"Moon-dancers"', '"Mr', '"Mrs', '"My', '"Never', '"Of', '"Oh', '"Once', '"Only', '"Or', '"That', '"The', '"Then', '"There', '"There:', '"This', '"We', '"Well', '"What', '"When', '"Why', '"Yes', '"Yes--quite', '"Yes--she\'s', '"You', '"deadening', '"dragged', '"effects";', '"interesting":', '"lift', '"obituary"', '"strongest', '"strongly"', '"sweetly"--and', "'", "'Are", "'It's", "'coming'", "'done'", "'subject", "'technique'", "'way", '(I', '(Though', ')', ',', '--', '.', 'A', 'Among', 'And', 'Arrt', 'As', 'At', 'Burlington', 'But', 'By', 'Carlo', 'Carlo;', 'Chicago', 'Claude', 'Croft', 'Croft)', 'Devonshire', "Don't", 'Dubarry_', 'Emperors', 'Florence', 'For', 'Gallery', 'Gideon', 'Gisburn', 'Gisburn!', "Gisburn's", 'Gisburn--as', 'Gisburn--fond', 'Grafton', 'Greek', 'Grindle', "Grindle's", 'Grindle:', 

In [9]:
vocab_size = len(all_words)
print(vocab_size)

1319


In [10]:
vocab = {token: integer for integer, token in enumerate(all_words)}
print(vocab)

{'"': 0, '"Ah': 1, '"Ah--I': 2, '"Be': 3, '"By': 4, '"Come': 5, '"Destroyed': 6, '"Don\'t': 7, '"Gisburns"': 8, '"Grindles': 9, '"Hang': 10, '"Has': 11, '"How': 12, '"I': 13, '"I\'d': 14, '"If': 15, '"It': 16, '"It\'s': 17, '"Jack': 18, '"Money\'s': 19, '"Moon-dancers"': 20, '"Mr': 21, '"Mrs': 22, '"My': 23, '"Never': 24, '"Of': 25, '"Oh': 26, '"Once': 27, '"Only': 28, '"Or': 29, '"That': 30, '"The': 31, '"Then': 32, '"There': 33, '"There:': 34, '"This': 35, '"We': 36, '"Well': 37, '"What': 38, '"When': 39, '"Why': 40, '"Yes': 41, '"Yes--quite': 42, '"Yes--she\'s': 43, '"You': 44, '"deadening': 45, '"dragged': 46, '"effects";': 47, '"interesting":': 48, '"lift': 49, '"obituary"': 50, '"strongest': 51, '"strongly"': 52, '"sweetly"--and': 53, "'": 54, "'Are": 55, "'It's": 56, "'coming'": 57, "'done'": 58, "'subject": 59, "'technique'": 60, "'way": 61, '(I': 62, '(Though': 63, ')': 64, ',': 65, '--': 66, '.': 67, 'A': 68, 'Among': 69, 'And': 70, 'Arrt': 71, 'As': 72, 'At': 73, 'Burlington

In [11]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {integer: token for token, integer in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[token] for token in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[integer] for integer in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [12]:
tokenizer = SimpleTokenizerV1(vocab)

In [13]:
text = "I have mentioned that Mrs. Gisburn was rich"

In [14]:
ids = tokenizer.encode(text)

In [15]:
print(ids)

[108, 627, 801, 1152, 127, 67, 91, 1254, 1003]


## Adding special context tokens (Tokens that are not in the training set)

In [16]:
text = "Hello, do you like tea. is this-- a test?"

In [17]:
#tokenizer.encode(text)

In [18]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(['<|endoftext|>', '<|unk|>'])

vocab = {token: integer for integer, token in enumerate(all_tokens)}

In [19]:
print(vocab)

{'"': 0, '"Ah': 1, '"Ah--I': 2, '"Be': 3, '"By': 4, '"Come': 5, '"Destroyed': 6, '"Don\'t': 7, '"Gisburns"': 8, '"Grindles': 9, '"Hang': 10, '"Has': 11, '"How': 12, '"I': 13, '"I\'d': 14, '"If': 15, '"It': 16, '"It\'s': 17, '"Jack': 18, '"Money\'s': 19, '"Moon-dancers"': 20, '"Mr': 21, '"Mrs': 22, '"My': 23, '"Never': 24, '"Of': 25, '"Oh': 26, '"Once': 27, '"Only': 28, '"Or': 29, '"That': 30, '"The': 31, '"Then': 32, '"There': 33, '"There:': 34, '"This': 35, '"We': 36, '"Well': 37, '"What': 38, '"When': 39, '"Why': 40, '"Yes': 41, '"Yes--quite': 42, '"Yes--she\'s': 43, '"You': 44, '"deadening': 45, '"dragged': 46, '"effects";': 47, '"interesting":': 48, '"lift': 49, '"obituary"': 50, '"strongest': 51, '"strongly"': 52, '"sweetly"--and': 53, "'": 54, "'Are": 55, "'It's": 56, "'coming'": 57, "'done'": 58, "'subject": 59, "'technique'": 60, "'way": 61, '(I': 62, '(Though': 63, ')': 64, ',': 65, '--': 66, '.': 67, 'A': 68, 'Among': 69, 'And': 70, 'Arrt': 71, 'As': 72, 'At': 73, 'Burlington

In [20]:
print(len(vocab))

1321


In [21]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {integer: token for token, integer in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [item if item in self.str_to_int else "<|unk|>" for item in preprocessed]
        ids = [self.str_to_int[token] for token in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[integer] for integer in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [22]:
text

'Hello, do you like tea. is this-- a test?'

In [23]:
tokenizer = SimpleTokenizerV2(vocab)

In [24]:
tokenizer.encode(text)

[1320, 65, 448, 1311, 755, 1141, 67, 699, 1169, 66, 199, 1320, 1320]

In [25]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea. is this -- a <|unk|> <|unk|>'

## Byte pair encoding

In [26]:
import tiktoken

In [27]:
tiktoken.__version__

'0.13.0'

In [28]:
tokenizer = tiktoken.get_encoding("gpt2")

In [29]:
tokenizer.encode("Hello world")

[15496, 995]

In [30]:
tokenizer.decode(tokenizer.encode("Hello world"))

'Hello world'

In [31]:
text = "Hello, do you like tea? <|endoftext|> In the sunlit terraces of some unknownPlace."

In [32]:
print(tokenizer.encode(text, allowed_special={"<|endoftext|>"}))

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 286, 617, 6439, 27271, 13]


## Data sampling with a sliding window

In [33]:
tokenizer = tiktoken.get_encoding("gpt2")

In [34]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)

In [35]:
print(len(enc_text))

5148


In [36]:
enc_sample = enc_text[50:]

In [37]:
context_size = 4

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

In [38]:
print(x)
print(y)

[290, 4920, 2241, 287]
[4920, 2241, 287, 257]


In [39]:
import torch

In [40]:
print(torch.__version__)

2.6.0+cu124


In [41]:
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use the sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1:i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [42]:
def create_dataloader_v1(txt, batch_size=8, max_length=256, stride=128, shuffle=True, drop_last=True, num_workers=0):
    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, drop_last=drop_last, num_workers=num_workers)
    return dataloader

In [43]:
dataloader = create_dataloader_v1(raw_text, max_length=4)

In [44]:
print(next(iter(dataloader)))

[tensor([[  526,   198,   198,  3347],
        [   11,  4844,   286,   262],
        [  198,    40,   423,  4750],
        [ 1517,   484,  1444,   616],
        [  284,   616,   835,   286],
        [  465,  3211,   832,  6164],
        [  656,   465,  1021,   757],
        [  407,  1972,   262, 18560]]), tensor([[  198,   198,  3347, 27846],
        [ 4844,   286,   262,  1633],
        [   40,   423,  4750,   326],
        [  484,  1444,   616,   705],
        [  616,   835,   286,  1762],
        [ 3211,   832,  6164,    25],
        [  465,  1021,   757,   438],
        [ 1972,   262, 18560,   438]])]


## Creating token embeddings

In [45]:
input_ids = torch.tensor([2, 3, 5, 1])

In [46]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(tokenizer.n_vocab, output_dim)

In [47]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035],
        [-0.5880,  0.3486,  0.6603],
        [-0.2196, -0.3792,  0.7671],
        ...,
        [-0.5931,  1.0895, -0.6854],
        [ 0.7447,  0.5803, -0.4246],
        [-0.3130,  0.7558, -1.2656]], requires_grad=True)


In [48]:
embedding_layer(torch.tensor([3]))

tensor([[-1.1925,  0.6984, -1.4097]], grad_fn=<EmbeddingBackward0>)

## Encoding word positions

In [49]:
vocab_size = tokenizer.n_vocab
output_dim = 256

torch.manual_seed(123)
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [50]:
max_length = 4
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=max_length, stride=max_length, shuffle=False)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [51]:
print(inputs)

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])


In [56]:
token_embedding = token_embedding_layer(inputs)
print(token_embedding.shape)
print(token_embedding)

torch.Size([8, 4, 256])
tensor([[[-6.3964e-02,  3.3174e-01,  1.0698e-01,  ...,  5.3491e-01,
          -8.0244e-01, -2.3238e+00],
         [-3.5248e-01,  3.5087e-01,  9.8728e-01,  ..., -1.8466e+00,
          -1.7034e+00,  3.2226e-01],
         [ 1.0017e+00,  9.2986e-01, -1.2633e+00,  ..., -1.2256e+00,
           1.1179e+00,  1.3427e-01],
         [ 7.9961e-01,  2.2837e+00, -6.5249e-01,  ..., -1.1217e+00,
           4.7057e-01,  1.5314e-01]],

        [[-1.0823e-01, -1.2723e+00, -1.2217e+00,  ..., -9.1995e-01,
           2.0073e+00, -1.4138e+00],
         [-2.4273e-01,  9.1447e-01,  1.0885e+00,  ..., -8.6509e-01,
           3.5269e+00,  7.2247e-01],
         [-5.4342e-01,  1.6203e+00,  1.2222e+00,  ...,  6.8139e-01,
          -1.4032e+00,  1.4922e-01],
         [-3.5035e-01, -9.3247e-01, -1.2900e+00,  ..., -1.4980e+00,
           1.3996e-01,  3.7301e-01]],

        [[ 6.7677e-02, -1.0757e+00,  1.3706e-01,  ..., -3.9116e-01,
          -1.0974e+00,  7.5906e-01],
         [-1.2561e+00,  3.1

In [53]:
context_length = max_length

torch.manual_seed(123)
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [54]:
pos_embedding = pos_embedding_layer(torch.arange(max_length))
print(pos_embedding.shape)

torch.Size([4, 256])


In [55]:
input_embedding = token_embedding + pos_embedding
print(input_embedding)

tensor([[[ 0.2734,  0.1540, -0.1966,  ...,  1.8686, -0.7253, -2.3760],
         [-0.1139,  0.4919, -0.3482,  ..., -1.8781, -2.7674,  1.2640],
         [-0.3135,  0.8622, -1.3983,  ..., -1.5438, -0.2756,  0.6569],
         [ 1.0575,  2.6257, -1.4693,  ..., -1.6056,  0.1993,  0.0757]],

        [[ 0.2291, -1.4501, -1.5252,  ...,  0.4138,  2.0844, -1.4660],
         [-0.0041,  1.0555, -0.2470,  ..., -0.8966,  2.4629,  1.6642],
         [-1.8586,  1.5526,  1.0872,  ...,  0.3633, -2.7968,  0.6718],
         [-0.0925, -0.5905, -2.1068,  ..., -1.9820, -0.1313,  0.2956]],

        [[ 0.4050, -1.2535, -0.1665,  ...,  0.9426, -1.0203,  0.7069],
         [-1.0175,  0.4591, -1.3149,  ...,  0.7143, -2.1019, -0.7233],
         [-1.1961,  0.6923, -1.0656,  ..., -0.3175, -0.5330, -0.8472],
         [ 0.2675,  0.9204, -0.5037,  ..., -0.6155, -1.4051, -1.2175]],

        ...,

        [[ 0.7313, -1.0724, -0.6057,  ..., -0.6354, -1.4791,  0.2751],
         [ 1.4171, -0.1835, -1.9796,  ..., -0.4246, -2.10